- hosts: harbor
  gather_facts: False
  remote_user: harbor
  become: yes
  become_user: root
  roles:
    - { role: commons }
    - { role: docker }
    - { role: lets_encrypt }
    - { role: harbor }