- name: Pre Installation
  hosts: localhost
  become: true
  tasks:
    - name: Update repositories
      apt:
        update_cache: true
    - name: Install packages
      apt:
        name: kubectl
        state: present

- name: Start cluster
  hosts: localhost
  tasks:
    - name: Enable Cluster monitoring
      ansible.builtin.shell: |
        az provider register --namespace Microsoft.OperationsManagement
        az provider register --namespace Microsoft.OperationalInsights
    - name: Create Cluster in Azure
      ansible.builtin.shell: az aks create --resource-group InfraProject --name InfraProjectCluster --node-count 1 --enable-addons monitoring --generate-ssh-keys
