# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: postgress-ingres
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: letsencrypt
# spec:
#   tls:
#   - hosts:
#     - hello-world-ingress.MY_CUSTOM_DOMAIN
#     secretName: tls-secret
#   rules:
#   - host: hello-world-ingress.MY_CUSTOM_DOMAIN
#     http:
#       paths:
#       - backend:
#           serviceName: aks-helloworld-one
#           servicePort: 80
#         path: /hello-world-one(/|$)(.*)
#       - backend:
#           serviceName: aks-helloworld-two
#           servicePort: 80
#         path: /hello-world-two(/|$)(.*)
#       - backend:
#           serviceName: aks-helloworld-one
#           servicePort: 80
#         path: /(.*)