- name: add certbot PPA
  apt_repository:
    repo: ppa:certbot/certbot
    state: present
- name: install certbot for Nginx
  apt:
    name: 'python-certbot-nginx'
    state: present
- name: check if certificate exists
  stat:
    path: /etc/letsencrypt/live/{{ domain_name }}/cert.pem
  register: cert_exists
- name: check if service is running on port 80
  wait_for:
    port: 80
    timeout: 10
    state: stopped
    msg: "Port 80 already allocated"
  register: service_status
  ignore_errors: yes
- name: cert_bot_exists
  debug:
    var: cert_exists
- name: debug cert_service_status_exists
  debug:
    var: service_status
- name: generate new certificate {{ domain_name }}
  shell: certbot certonly --standalone --noninteractive --agree-tos --email {{ cert_admin_email }} -d {{ domain_name }}
  when:
    - cert_exists.stat.exists == false
    - service_status.state == "stopped"