- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: install required packages
  apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  vars:
    packages:
      - python3
      - curl
      - wget
      - python3-pip
- name: stop nginx
  systemd:
    name: nginx
    enabled: no
    state: stopped
- name: remove nginx package
  apt:
    name: nginx
    state: absent
